"""
GitHub Pull Request Creator
Creates pull requests on GitHub from generated code using the GitHub REST API.
"""

import requests
import base64
import re
from datetime import datetime
from config import GITHUB_TOKEN


def create_pull_request(
    repo_url: str,
    files: list[dict],
    branch_name: str = None,
    commit_message: str = "Add code generated by DevCopilot",
    pr_title: str = "DevCopilot: Generated Code",
    pr_body: str = "",
    github_token: str = None,
) -> dict:
    """
    Create a GitHub pull request with the given files.

    Args:
        repo_url: GitHub repository URL
        files: List of dicts with 'path' and 'content' keys
        branch_name: Branch name (auto-generated if None)
        commit_message: Commit message
        pr_title: Pull request title
        pr_body: Pull request description
        github_token: GitHub token (falls back to env var)

    Returns:
        dict with 'pr_url', 'pr_number', 'branch' on success, or 'error'
    """
    token = github_token or GITHUB_TOKEN
    if not token or len(token) < 10:
        return {"error": "A valid GitHub token is required to create pull requests. Please provide one in the sidebar."}

    # Parse owner/repo
    parts = repo_url.rstrip("/").removesuffix(".git").split("/")
    owner, repo = parts[-2], parts[-1]

    headers = {
        "Accept": "application/vnd.github.v3+json",
        "Authorization": f"token {token}",
    }
    api_base = f"https://api.github.com/repos/{owner}/{repo}"

    try:
        # Step 1: Get default branch and its latest commit SHA
        repo_resp = requests.get(api_base, headers=headers, timeout=15)
        repo_resp.raise_for_status()
        repo_info = repo_resp.json()
        default_branch = repo_info.get("default_branch", "main")

        ref_resp = requests.get(
            f"{api_base}/git/refs/heads/{default_branch}",
            headers=headers, timeout=15,
        )
        ref_resp.raise_for_status()
        base_sha = ref_resp.json()["object"]["sha"]

        # Step 2: Create a new branch
        if not branch_name:
            timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
            branch_name = f"devcopilot/{timestamp}"

        # Sanitize branch name
        branch_name = re.sub(r'[^a-zA-Z0-9/_-]', '-', branch_name)

        create_ref_resp = requests.post(
            f"{api_base}/git/refs",
            headers=headers,
            json={
                "ref": f"refs/heads/{branch_name}",
                "sha": base_sha,
            },
            timeout=15,
        )
        if create_ref_resp.status_code == 422:
            # Branch already exists, get its SHA
            ref_resp2 = requests.get(
                f"{api_base}/git/refs/heads/{branch_name}",
                headers=headers, timeout=15,
            )
            if not ref_resp2.ok:
                return {"error": f"Branch '{branch_name}' already exists and could not be accessed."}
        elif not create_ref_resp.ok:
            return {"error": f"Failed to create branch: {create_ref_resp.json().get('message', create_ref_resp.text)}"}

        # Step 3: Create/update files on the new branch
        created_files = []
        for file_info in files:
            file_path = file_info.get("path", "").strip()
            file_content = file_info.get("content", "")

            if not file_path or not file_content:
                continue

            # Check if file exists (to get its SHA for update)
            existing_resp = requests.get(
                f"{api_base}/contents/{file_path}?ref={branch_name}",
                headers=headers, timeout=15,
            )
            file_sha = None
            if existing_resp.ok:
                file_sha = existing_resp.json().get("sha")

            # Create or update file
            payload = {
                "message": commit_message,
                "content": base64.b64encode(file_content.encode("utf-8")).decode("ascii"),
                "branch": branch_name,
            }
            if file_sha:
                payload["sha"] = file_sha

            put_resp = requests.put(
                f"{api_base}/contents/{file_path}",
                headers=headers,
                json=payload,
                timeout=15,
            )
            if put_resp.ok:
                created_files.append(file_path)
            else:
                return {"error": f"Failed to create file '{file_path}': {put_resp.json().get('message', put_resp.text)}"}

        if not created_files:
            return {"error": "No files were committed. Make sure file paths and content are provided."}

        # Step 4: Create pull request
        if not pr_body:
            pr_body = (
                f"## 🤖 Generated by DevCopilot\n\n"
                f"This PR was auto-generated by DevCopilot's Code Generation Agent.\n\n"
                f"### Files\n" +
                "\n".join([f"- `{f}`" for f in created_files]) +
                f"\n\n---\n*Created with [DevCopilot](https://github.com) AI Codebase Assistant*"
            )

        pr_resp = requests.post(
            f"{api_base}/pulls",
            headers=headers,
            json={
                "title": pr_title,
                "body": pr_body,
                "head": branch_name,
                "base": default_branch,
            },
            timeout=15,
        )

        if not pr_resp.ok:
            error_msg = pr_resp.json().get("message", pr_resp.text)
            # If PR already exists for this branch
            if "A pull request already exists" in error_msg:
                return {
                    "pr_url": f"https://github.com/{owner}/{repo}/compare/{branch_name}",
                    "branch": branch_name,
                    "files_committed": created_files,
                    "message": f"Files committed to '{branch_name}'. A PR already exists for this branch.",
                }
            return {"error": f"Failed to create PR: {error_msg}"}

        pr_data = pr_resp.json()
        return {
            "pr_url": pr_data.get("html_url", ""),
            "pr_number": pr_data.get("number"),
            "branch": branch_name,
            "files_committed": created_files,
            "message": f"Pull request #{pr_data.get('number')} created successfully!",
        }

    except requests.exceptions.RequestException as e:
        return {"error": f"GitHub API error: {str(e)}"}
    except Exception as e:
        return {"error": f"Unexpected error: {str(e)}"}
