/**
 * DevCopilot API Service
 * Handles all communication with the FastAPI backend.
 */

import axios from 'axios';

const API_BASE = import.meta.env.VITE_API_BASE || '/api';

const api = axios.create({
  baseURL: API_BASE,
  timeout: 300000, // 5 min default timeout
  headers: {
    'Content-Type': 'application/json',
  },
});

/**
 * Ingest a GitHub repository.
 * @param {string} repoUrl - GitHub repository URL
 * @param {string} [githubToken] - Optional GitHub access token
 * @returns {Promise<Object>} Ingestion result with stats
 */
export async function ingestRepository(repoUrl, githubToken = null) {
  const payload = { repo_url: repoUrl };
  if (githubToken) {
    payload.github_token = githubToken;
  }
  const response = await api.post('/ingest', payload, { timeout: 30000 }); // Backend returns immediately
  return response.data;
}

/**
 * Send a query to the multi-agent system.
 * @param {string} query - User's question or request
 * @param {string} [agentType] - Force specific agent (qa, codegen, lld, pr)
 * @param {string} [repoUrl] - Repo URL for PR analysis
 * @param {number} [prNumber] - PR number for analysis
 * @returns {Promise<Object>} Agent response with explanation log
 */
export async function sendQuery(query, agentType = null, repoUrl = null, prNumber = null) {
  const payload = { query };
  if (agentType) payload.agent_type = agentType;
  if (repoUrl) payload.repo_url = repoUrl;
  if (prNumber) payload.pr_number = prNumber;

  const response = await api.post('/query', payload, { timeout: 300000 });
  return response.data;
}

/**
 * Get current system status.
 * @returns {Promise<Object>} Status with ingestion state and stats
 */
export async function getStatus() {
  const response = await api.get('/status');
  return response.data;
}

/**
 * Get knowledge graph statistics.
 * @returns {Promise<Object>} Graph stats with sample nodes
 */
export async function getGraphStats() {
  const response = await api.get('/graph-stats');
  return response.data;
}

/**
 * Create a GitHub Pull Request with generated code.
 * @param {Object} params - PR creation parameters
 * @returns {Promise<Object>} PR result with pr_url, pr_number
 */
export async function createPullRequest({ repoUrl, githubToken, files, branchName, commitMessage, prTitle, prBody }) {
  const payload = {
    repo_url: repoUrl,
    files,
    commit_message: commitMessage || 'Add code generated by DevCopilot',
    pr_title: prTitle || 'DevCopilot: Generated Code',
  };
  if (githubToken) payload.github_token = githubToken;
  if (branchName) payload.branch_name = branchName;
  if (prBody) payload.pr_body = prBody;

  const response = await api.post('/create-pr', payload, { timeout: 60000 });
  return response.data;
}

export default api;
